name: Generate Pacman daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: abozanona/pacman-contribution-graph@0.0.2
        with:
          github_user_name: shaeakh
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/pacman-contribution-graph.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output-pacman
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
